repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.4  # Use latest as needed
    hooks:
      - id: uv-lock   # Ensures uv.lock up-to-date with pyproject.toml
      - id: uv-export # Keeps requirements.txt synced with uv.lock

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        name: "mypy"
        exclude: ^tests/

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
